### ISSUE TITLE
Run `azd up` fail in codespace and windows

### ISSUE THREAD

**Issue by v-jiaodi** [tataraba/musicbinder-azd#2]
**Describe the issue:**
When executing `azd up` according to [README.md](https://github.com/tataraba/musicbinder-azd#readme), the error is as follows:

![image](https://github.com/tataraba/musicbinder-azd/assets/80496810/89a6788b-b02d-400f-9800-dbc3da0bd7cd)

**Repro Steps:**
1. Run `azd auth login`
2. Run `azd up`

**Environment:**
- OS: Windows desktop and CodeSpace.

**Expected behavior:**
 Run `azd up` can pass.

@tataraba ,@rajeshkamal5050 for notification.

**Comment by tataraba** [comment]
Looks like it was an issue of nested quotes. Azure doesn't like the nested single quotes, so I replaced the command line to match another sample app in AZD Templates [Python to-do app](https://github.com/Azure-Samples/todo-python-mongo/blob/main/infra/app/api.bicep)

![image](https://github.com/tataraba/musicbinder-azd/assets/46942991/bbc44ec7-6f06-4111-9c00-16776da29b28)

This was fixed.
