### ISSUE TITLE
Unable to find `use this template` button in repo

### ISSUE THREAD

**Issue by v-jiaodi** [tataraba/musicbinder-azd#3]
**Describe the issue:**
This button `use this template` is not present in the repo : https://github.com/tataraba/musicbinder-azd

![image](https://github.com/tataraba/musicbinder-azd/assets/80496810/05caf878-5700-49c3-8432-b6f62651b5dd)

**Expected behavior:**
Able to find `use this template` button or update README.md.

@tataraba , @rajeshkamal5050 for notification.

**Comment by tataraba** [comment]
Oops. Had forgotten to turn this into a template repository. Should be done now, thanks!
